### ISSUE TITLE
Tile is occasionally overwritten by background color

### ISSUE THREAD

**Issue by BartMassey** [KappaDistributive/rs2048#10]
Google Chrome 71.0.3559.6 on Debian Linux. Under some hard-to-define conditions, I'm seeing a white square where one or two of the game tiles should be. This happens both with the online demo and when compiled locally.

**Comment by KappaDistributive** [comment]
Thanks for the bug report!

I've yet to see this happen on my machine. If someone can provide instructions on how to reproduce this bug, I'd highly appreciate it.

**Comment by BartMassey** [comment]
Here's a screenshot from my box. I just upgraded my box and Chrome in case it was version thing or something. I had just dropped an eight on the now-white square to make 16. For some reason, 16 seems to be the most common white-square number, but it also happens with larger numbers. I don't recall seeing it with a 1-digit number yet?

![rs2048-bug-2019-01-04](https://user-images.githubusercontent.com/117151/50681715-532be080-0fc1-11e9-841b-212a02ac8675.png)

**Comment by BartMassey** [comment]
Yeah, I have only ever seen it fail on 16 and 128. I'm going to guess that there's a numeric width calculation fail…

Nope, found it. Take a careful look at `background_color()` in `game.rs`. You'll find it too. :-) The funny thing is that sometimes the 16 or 128 would get painted with the game background color, so it wasn't 100% consistent. Probably another bug there somewhere. :-)

**Comment by KappaDistributive** [comment]
Thank you for troubleshooting this!

I agree that there probably is another bug related to this but decided to close this issue for now and reopen it if the need arises.
