### ISSUE TITLE
Wrapping game in Rc<RefCell> ?

### ISSUE THREAD

**Issue by BartMassey** [KappaDistributive/rs2048#11]
I don't see any reason why the game needs to be wrapped in `Rc<RefCell>` in `main.rs`? All those calls to `.borrow()` and `.borrow_mut()` in `main.rs` would then be unnecessary. Removing this compiles under all the different `stdweb` versions.

**Comment by KappaDistributive** [comment]
There is indeed no reason to do so. It's an artifact of prior attempts to get WASM working.

I'll leave this open as a good first issue to work on for a bit.

**Comment by KappaDistributive** [comment]
#21 changed the way the refresh/redraw cycle is handled and to my, admittedly very limited knowledge about ownership in Rust, it now seems to me that we can no longer avoid wrapping game in `Rc<RefCell>`.

I'd appreciate some feedback on this.

**Comment by BartMassey** [comment]
See pull request #23, in which I clean things up a bit :-) .
