### ISSUE TITLE
Extend tile color palette

### ISSUE THREAD

**Issue by KappaDistributive** [KappaDistributive/rs2048#4]
Right now, tile color information only exists up to a tile of size 2048. Extend this color palette up to 2^17 -- the maximal possible tile.

**Comment by crcheng** [comment]
Hi @KappaDistributive,
First-time contributor here and I found your repo on the `/rust` subreddit. I wanna work on this!

**Comment by KappaDistributive** [comment]
@crcheng Awesome! There is a function 'foreground_colour' in src/game.rs that handles the colour of tiles to be drawn depending on their current value but it only handles tiles up to a value of 2^11=2048, so you need to add  6 more colours to guarantee that we'll never run out.

You can extend the current colour palette, if you like, but you're also more than welcome if you want to cook up your own.

If you have any questions, please feel free to reach out to me.

**Comment by crcheng** [comment]
@KappaDistributive super thanks for the info and warm welcome! I'll let you know once I've cooked something up. Thanks again!
