### ISSUE TITLE
Implement a scoreboard

### ISSUE THREAD

**Issue by KappaDistributive** [KappaDistributive/rs2048#7]
Implement a scoreboard. This can range anywhere from a simple text field displaying the current score to a much wilder system to keep track of the score with flashy animations that trigger whenever the player reaches a new milestone.

**Comment by BartMassey** [comment]
Store the scoreboard server-side or browser-side (or both)? The former allows players to compare scores, at least within the same server, the latter is "free" and would be a good exploration of using browser nonvolatile storage.

The coolest plan would be to implement a global REST score service, but this would be a pain. You'd need someone with a permanent commitment to hosting and maintaining the service; also, it would be hard to keep server operators from cheating wildly.

**Comment by KappaDistributive** [comment]
I intentionally phrase these issues open ended so that the potential contributors can decide themselves what they may want to add and feel comfortable tackling.

As a first step I suggest implementing a very simple scoreboard in memory. Basically just an indicator of the player's current score.

As a next step, we could use the HTML5 Web Storage to store scores browser-side.

Storing a sort of leaderbord server-site is an interesting project and I'd like very much to see this happen at some point. But for now, I'd say, we should keep these problems as simple as possible to realize to offer plenty of 'low hanging fruit' to beginners in Rust. After all, that's the intended purpose of this project.
